### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by stefanusgusega** [pmk-itb/api-pmb#1]
Design database that corresponds to PMB 2021 form front end. It should be done in our Google Drive for this project. This is the [link](https://drive.google.com/file/d/1o7k0vVkctkD7shCDaHwTlhEkydw8x58U/view?usp=sharing).

**Comment by stefanusgusega** [comment]
- [ ] Make table for KTB as a separated table with Pemuridan

**Comment by samnap11** [comment]
I left a comment but I think it's very good!
